### ISSUE TITLE
Add ZED to description

### ISSUE THREAD

**Issue by khaledhazime** [robofeiathome/hera_description#1]
Add ZED2 model to HERA description instead of Kinect

- [x] ZED2 model to "meshes"folder
- [x] Model to URDF
- [x] Camera plugins to use STEREO camera on Gazebo
- [x] Create parameters to use kinect or zed and action

**Comment by flomaidar** [comment]
Não sei se os plug-ins do gazebo estao funcionando... usei os mesmos do kinect. Se for usar na simulação, alguém da visão deveria ver isso.

**Comment by khaledhazime** [comment]
> Não sei se os plug-ins do gazebo estao funcionando... usei os mesmos do kinect. Se for usar na simulação, alguém da visão deveria ver isso.

Eu tava pesquisando e parece que não tem nenhum plugin oficial da StereoLabs, mas tem um do próprio gazebo de [multicamera](https://classic.gazebosim.org/tutorials?tut=ros_gzplugins#Multicamera)
